{
 "title": "Vitess Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cluster Query Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Wide Queries Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(vttablet_query_counts[1m]))"
    }
   ]
  },
  {
   "title": "Vttablet Query Latency",
   "type": "graph",
   "description": "Query Latency at various percentiles",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(vttablet_mysql_bucket[10m])) by (operation,le))",
     "legendFormat": "50th Percentile {{operation}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vttablet_mysql_bucket[10m])) by (operation,le))",
     "legendFormat": "95th Percentile {{operation}}"
    }
   ]
  },
  {
   "title": "Table Rows",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "sum(vttablet_table_rows) by (table)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  { "title": "Connection Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Accepted Connections per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(vttablet_mysql_server_conn_accepted[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VTGate Current Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vtgate_mysql_server_conn_count", "legendFormat": "{{pod}} mysql connections" },
    { "expr": "vtgate_conn_count", "legendFormat": "{{pod}} grpc connections" }
   ]
  },
  {
   "title": "Tablet Available Connections Pool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vttablet_transaction_pool_available",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}