engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
    - "**.go"
    - "**.sh"

# Ignore generated code.
exclude_paths:
- "go/vt/proto/"
- "go/vt/sqlparser/sql.go"
- "py/util/grpc_with_metadata.py"
- "travis/install_grpc.sh"
