run:
  timeout: 10m

linters-settings:
  goimports:
    local-prefixes: vitess.io/vitess

linters:
  disable-all: true
  enable:
    # Defaults
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck

    # Extras
    - gofmt
    - goimports

# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.34.x # use the fixed version to not introduce new linters unexpectedly
