/*
Copyright 2021 The Vitess Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package asthelpergen

import (
	"go/types"

	"github.com/dave/jennifer/jen"
)

const inputName = "Input"

type inputGen struct {
	file *jen.File
}

var _ generator = (*inputGen)(nil)

func newInputGen(pkgname string) *inputGen {
	file := jen.NewFile(pkgname)
	file.HeaderComment(licenseFileHeader)
	file.HeaderComment("Code generated by ASTHelperGen. DO NOT EDIT.")

	return &inputGen{
		file: file,
	}
}

func (v *inputGen) genFile() (string, *jen.File) {
	return "ast_input.go", v.file
}

func (v *inputGen) interfaceMethod(t types.Type, iface *types.Interface, spi generatorSPI) error {
	if !shouldAdd(t, spi.iface()) {
		return nil
	}
	/*
		func Input(in AST) []AST {
			if in == nil {
				return nil
			}
			switch a := inA.(type) {
			case *SubImpl:
				return VisitSubImpl(a, b)
			default:
				return false, nil
			}
		}
	*/
	stmts := []jen.Code{
		jen.If(jen.Id("in == nil").Block(returnNil())),
	}

	var cases []jen.Code
	_ = spi.findImplementations(iface, func(t types.Type) error {
		if _, ok := t.Underlying().(*types.Interface); ok {
			return nil
		}
		typeString := types.TypeString(t, noQualifier)
		funcName := inputName + printableTypeName(t)
		spi.addType(t)
		caseBlock := jen.Case(jen.Id(typeString)).Block(
			jen.Return(jen.Id(funcName).Call(jen.Id("in"))),
		)
		cases = append(cases, caseBlock)
		return nil
	})

	cases = append(cases,
		jen.Default().Block(
			jen.Comment("this should never happen"),
			returnNil(),
		))

	stmts = append(stmts, jen.Switch(jen.Id("in := in.(type)").Block(
		cases...,
	)))

	v.inputFunc(t, stmts)
	return nil
}

func (v *inputGen) structMethod(t types.Type, strct *types.Struct, spi generatorSPI) error {
	/*
		func VisitRefOfRefContainer(in *RefContainer, f func(node AST) (kontinue bool, err error)) (bool, error) {
			if cont, err := f(in); err != nil || !cont {
				return false, err
			}
			if k, err := VisitRefOfLeaf(in.ASTImplementationType, f); err != nil || !k {
				return false, err
			}
			if k, err := VisitAST(in.ASTType, f); err != nil || !k {
				return false, err
			}
			return true, nil
		}
	*/

	stmts := inputsFromAllTheFields(strct, spi)
	v.inputFunc(t, stmts)

	return nil
}

func inputsFromAllTheFields(strct *types.Struct, spi generatorSPI) []jen.Code {
	output := []jen.Code{
		visitIn(),
	}
	for i := 0; i < strct.NumFields(); i++ {
		field := strct.Field(i)
		if types.Implements(field.Type(), spi.iface()) {
			spi.addType(field.Type())
			addField := inputChild(jen.Id("in").Dot(field.Name()))
			output = append(output, addField)
			continue
		}
		slice, isSlice := field.Type().(*types.Slice)
		if isSlice && types.Implements(slice.Elem(), spi.iface()) {
			spi.addType(slice.Elem())
			output = append(output, jen.For(jen.Id("_, el := range in."+field.Name())).Block(
				visitChild(slice.Elem(), jen.Id("el")),
			))
		}
	}
	output = append(output, returnNil())
	return output
}

func (v *inputGen) ptrToStructMethod(t types.Type, strct *types.Struct, spi generatorSPI) error {
	if !shouldAdd(t, spi.iface()) {
		return nil
	}

	/*
		func VisitRefOfRefContainer(in *RefContainer, f func(node AST) (kontinue bool, err error)) (bool, error) {
			if in == nil {
				return true, nil
			}
			if cont, err := f(in); err != nil || !cont {
				return false, err
			}
			if k, err := VisitRefOfLeaf(in.ASTImplementationType, f); err != nil || !k {
				return false, err
			}
			if k, err := VisitAST(in.ASTType, f); err != nil || !k {
				return false, err
			}
			return true, nil
		}
	*/

	stmts := []jen.Code{
		jen.If(jen.Id("in == nil").Block(returnNil())),
	}
	stmts = append(stmts, visitAllStructFields(strct, spi)...)
	v.inputFunc(t, stmts)

	return nil
}

func (v *inputGen) ptrToBasicMethod(t types.Type, _ *types.Basic, spi generatorSPI) error {
	if !shouldAdd(t, spi.iface()) {
		return nil
	}

	stmts := []jen.Code{
		jen.Comment("ptrToBasicMethod"),
	}

	v.inputFunc(t, stmts)

	return nil
}

func (v *inputGen) sliceMethod(t types.Type, slice *types.Slice, spi generatorSPI) error {
	if !shouldAdd(t, spi.iface()) {
		return nil
	}

	if !shouldAdd(slice.Elem(), spi.iface()) {
		return v.visitNoChildren(t, spi)
	}

	stmts := []jen.Code{
		jen.If(jen.Id("in == nil").Block(returnNil())),
		visitIn(),
		jen.For(jen.Id("_, el := range in")).Block(
			visitChild(slice.Elem(), jen.Id("el")),
		),
		returnNil(),
	}

	v.inputFunc(t, stmts)

	return nil
}

func (v *inputGen) basicMethod(t types.Type, basic *types.Basic, spi generatorSPI) error {
	if !shouldAdd(t, spi.iface()) {
		return nil
	}

	return v.visitNoChildren(t, spi)
}

func (v *inputGen) visitNoChildren(t types.Type, spi generatorSPI) error {
	stmts := []jen.Code{
		jen.Id("_, err := f(in)"),
		jen.Return(jen.Err()),
	}

	v.inputFunc(t, stmts)

	return nil
}

func (v *inputGen) inputFunc(t types.Type, stmts []jen.Code) {
	typeString := types.TypeString(t, noQualifier)
	funcName := inputName + printableTypeName(t)
	funcDecl := jen.Func().
		Id(funcName).
		Call(jen.Id("in").Id(typeString)).Call(jen.Id("inputs").Id("[]SQLNode")).
		Block(stmts...)
	v.file.Add(funcDecl)
}
