name: Bug Report
description: You're experiencing an issue with Vitess that is different than the documented behavior.
title: ""
labels: ["Type: Bug", "Needs Triage"]
body:
  - type: textarea
    id: overview-of-the-issue
    attributes:
      label: Overview of the Issue
      description: A paragraph or two about the issue you're experiencing.
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: A paragraph or two about the issue you're experiencing.
      placeholder: |
        1. Deploy the following `vschema`:
          ```javascript
          {
            "sharded": true,
            "vindexes": {
              "hash": {
                "type": "hash"
              },
            "tables": {
              "user": {
                "column_vindexes": [
                  {
                    "column": "user_id",
                    "name": "hash"
                  }
                ]
              }
            }
          }
          ```
        2. Deploy the following `schema`:
            ```sql
            create table user(user_id bigint, name varchar(128), primary key(user_id));
            ```
        3. Run `SELECT...`
        4. View error
      value: ""
      render: markdown
    validations:
      required: true

  - type: textarea
    id: binary-version
    attributes:
      label: Binary Version
      description: Tell us which version of Vitess you're using.
      placeholder: |
        example:
        ```sh
        giaquinti@workspace:~$ vtgate --version
        Version: a95cf5d (Git branch 'HEAD') built on Fri May 18 16:54:26 PDT 2018 by giaquinti@workspace using go1.10 linux/amd64
        ```
      value: ""
      render: shell
    validations:
      required: true

  - type: textarea
    id: os-and-env
    attributes:
      label: Operating System and Environment details
      description: OS, Architecture, and any other information you can provide about the environment.
      placeholder: |
        - Operating system (output of `cat /etc/os-release`)
        - Kernel version (output of `uname -sr`)
        - Architecture (output of `uname -m`)
      value: ""
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Fragments
      description: Include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the gist (https://gist.github.com/) of the log instead of posting it in the issue. This will be automatically formatted into code, so no need for backticks.
      render: shell
