// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: vtboost.proto

package vtboost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CachedQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sql      string `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	Keyspace string `protobuf:"bytes,4,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
}

func (x *CachedQuery) Reset() {
	*x = CachedQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CachedQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CachedQuery) ProtoMessage() {}

func (x *CachedQuery) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CachedQuery.ProtoReflect.Descriptor instead.
func (*CachedQuery) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{0}
}

func (x *CachedQuery) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *CachedQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CachedQuery) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *CachedQuery) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

type AddQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*CachedQuery `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *AddQueryRequest) Reset() {
	*x = AddQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQueryRequest) ProtoMessage() {}

func (x *AddQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQueryRequest.ProtoReflect.Descriptor instead.
func (*AddQueryRequest) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{1}
}

func (x *AddQueryRequest) GetQueries() []*CachedQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type RemoveQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queries []*RemoveQueryRequest_Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *RemoveQueryRequest) Reset() {
	*x = RemoveQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveQueryRequest) ProtoMessage() {}

func (x *RemoveQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveQueryRequest.ProtoReflect.Descriptor instead.
func (*RemoveQueryRequest) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveQueryRequest) GetQueries() []*RemoveQueryRequest_Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

type ListQueriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListQueriesRequest) Reset() {
	*x = ListQueriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueriesRequest) ProtoMessage() {}

func (x *ListQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueriesRequest.ProtoReflect.Descriptor instead.
func (*ListQueriesRequest) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{3}
}

type ListQueriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeVersion uint64         `protobuf:"varint,1,opt,name=recipe_version,json=recipeVersion,proto3" json:"recipe_version,omitempty"`
	Queries       []*CachedQuery `protobuf:"bytes,2,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *ListQueriesResponse) Reset() {
	*x = ListQueriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueriesResponse) ProtoMessage() {}

func (x *ListQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueriesResponse.ProtoReflect.Descriptor instead.
func (*ListQueriesResponse) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{4}
}

func (x *ListQueriesResponse) GetRecipeVersion() uint64 {
	if x != nil {
		return x.RecipeVersion
	}
	return 0
}

func (x *ListQueriesResponse) GetQueries() []*CachedQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type RecipeChangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Added   int64 `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Removed int64 `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
}

func (x *RecipeChangeResponse) Reset() {
	*x = RecipeChangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecipeChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeChangeResponse) ProtoMessage() {}

func (x *RecipeChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeChangeResponse.ProtoReflect.Descriptor instead.
func (*RecipeChangeResponse) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{5}
}

func (x *RecipeChangeResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *RecipeChangeResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type RemoveQueryRequest_Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Remove:
	//
	//	*RemoveQueryRequest_Query_Name
	//	*RemoveQueryRequest_Query_PublicId
	Remove isRemoveQueryRequest_Query_Remove `protobuf_oneof:"remove"`
}

func (x *RemoveQueryRequest_Query) Reset() {
	*x = RemoveQueryRequest_Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vtboost_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveQueryRequest_Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveQueryRequest_Query) ProtoMessage() {}

func (x *RemoveQueryRequest_Query) ProtoReflect() protoreflect.Message {
	mi := &file_vtboost_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveQueryRequest_Query.ProtoReflect.Descriptor instead.
func (*RemoveQueryRequest_Query) Descriptor() ([]byte, []int) {
	return file_vtboost_proto_rawDescGZIP(), []int{2, 0}
}

func (m *RemoveQueryRequest_Query) GetRemove() isRemoveQueryRequest_Query_Remove {
	if m != nil {
		return m.Remove
	}
	return nil
}

func (x *RemoveQueryRequest_Query) GetName() string {
	if x, ok := x.GetRemove().(*RemoveQueryRequest_Query_Name); ok {
		return x.Name
	}
	return ""
}

func (x *RemoveQueryRequest_Query) GetPublicId() string {
	if x, ok := x.GetRemove().(*RemoveQueryRequest_Query_PublicId); ok {
		return x.PublicId
	}
	return ""
}

type isRemoveQueryRequest_Query_Remove interface {
	isRemoveQueryRequest_Query_Remove()
}

type RemoveQueryRequest_Query_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type RemoveQueryRequest_Query_PublicId struct {
	PublicId string `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3,oneof"`
}

func (*RemoveQueryRequest_Query_Name) isRemoveQueryRequest_Query_Remove() {}

func (*RemoveQueryRequest_Query_PublicId) isRemoveQueryRequest_Query_Remove() {}

var File_vtboost_proto protoreflect.FileDescriptor

var file_vtboost_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x74, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x76, 0x74, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x0b, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x41, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x71, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x74, 0x62,
	0x6f, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x99, 0x01, 0x0a, 0x12, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x3b, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x76, 0x74, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x46, 0x0a,
	0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x13, 0x4c,
	0x69, 0x73, 0x74, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x07, 0x71, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x74, 0x62,
	0x6f, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x64, 0x42, 0x26, 0x5a, 0x24, 0x76, 0x69, 0x74, 0x65, 0x73, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x76,
	0x69, 0x74, 0x65, 0x73, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x74, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vtboost_proto_rawDescOnce sync.Once
	file_vtboost_proto_rawDescData = file_vtboost_proto_rawDesc
)

func file_vtboost_proto_rawDescGZIP() []byte {
	file_vtboost_proto_rawDescOnce.Do(func() {
		file_vtboost_proto_rawDescData = protoimpl.X.CompressGZIP(file_vtboost_proto_rawDescData)
	})
	return file_vtboost_proto_rawDescData
}

var file_vtboost_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vtboost_proto_goTypes = []interface{}{
	(*CachedQuery)(nil),              // 0: vtboost.CachedQuery
	(*AddQueryRequest)(nil),          // 1: vtboost.AddQueryRequest
	(*RemoveQueryRequest)(nil),       // 2: vtboost.RemoveQueryRequest
	(*ListQueriesRequest)(nil),       // 3: vtboost.ListQueriesRequest
	(*ListQueriesResponse)(nil),      // 4: vtboost.ListQueriesResponse
	(*RecipeChangeResponse)(nil),     // 5: vtboost.RecipeChangeResponse
	(*RemoveQueryRequest_Query)(nil), // 6: vtboost.RemoveQueryRequest.Query
}
var file_vtboost_proto_depIdxs = []int32{
	0, // 0: vtboost.AddQueryRequest.queries:type_name -> vtboost.CachedQuery
	6, // 1: vtboost.RemoveQueryRequest.queries:type_name -> vtboost.RemoveQueryRequest.Query
	0, // 2: vtboost.ListQueriesResponse.queries:type_name -> vtboost.CachedQuery
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vtboost_proto_init() }
func file_vtboost_proto_init() {
	if File_vtboost_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vtboost_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CachedQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQueriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListQueriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecipeChangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vtboost_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveQueryRequest_Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vtboost_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*RemoveQueryRequest_Query_Name)(nil),
		(*RemoveQueryRequest_Query_PublicId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vtboost_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtboost_proto_goTypes,
		DependencyIndexes: file_vtboost_proto_depIdxs,
		MessageInfos:      file_vtboost_proto_msgTypes,
	}.Build()
	File_vtboost_proto = out.File
	file_vtboost_proto_rawDesc = nil
	file_vtboost_proto_goTypes = nil
	file_vtboost_proto_depIdxs = nil
}
