topology:
  cells:
    - name: "zone1"
      etcd:
        replicas: 1
      vtctld:
        replicas: 1
      vtgate:
        replicas: 1
      mysqlProtocol:
        enabled: true
        authType: "none"
      keyspaces:
        - name: "ks"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 2
                    enableSemisync: false
                    enableReplReporter: true
              copySchema:
                source: "recoveryks/0"
                tables:
                  - "employee"
        - name: "recoveryks"
          shards:
            - name: "0"
              tablets:
                - type: "replica"
                  vttablet:
                    replicas: 1
                    enableSemisync: false
                    enableReplReporter: false
                    initDBName: "employee"
                    extraFlags:
                      db_host: "172.19.4.121"
                      db_port: "3306"
                      db_dba_user: "root"
                      db_dba_password: "root"
                      db_app_user: "root"
                      db_app_password: "root"
                      db_filtered_user: "root"
                      db_filtered_password: "root"
                      db_allprivs_user: "root"
                      db_allprivs_password: "root"
                      db_repl_user: "root"
                      db_repl_password: "root"
etcd:
  replicas: 1
  resources:

vtctld:
  serviceType: "NodePort"
  resources:

vtgate:
  serviceType: "NodePort"
  resources:

vttablet:
  mysqlSize: "prod"
  resources:
  mysqlResources:

vtworker:
  resources:

pmm:
  enabled: false

orchestrator:
  enabled: false
