version: '2.1'

volumes:
  vol-db:

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_DATABASE: ${MYSQL_DB:-commerce}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpass}
    volumes:
      - vol-db:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d/
      - ./mysql/log:/var/log/mysql
    command: "--server-id=1 --log-bin=mysql-bin --general_log=1 --slow_query_log=1"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 10s
      retries: 10
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: rmsoft
    ports:
      - "8081:8080"
