/*
Copyright 2021 The Vitess Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by Sizegen. DO NOT EDIT.

package watcher

import hack "vitess.io/vitess/go/hack"

type cachedObject interface {
	CachedSize(alloc bool) int64
}

func (cached *View) CachedSize(alloc bool) int64 {
	if cached == nil {
		return int64(0)
	}
	size := int64(0)
	if alloc {
		size += int64(160)
	}
	// field name string
	size += hack.RuntimeAllocSize(int64(len(cached.name)))
	// field schema []*vitess.io/vitess/go/vt/proto/query.Field
	{
		size += hack.RuntimeAllocSize(int64(cap(cached.schema)) * int64(8))
		for _, elem := range cached.schema {
			size += elem.CachedSize(true)
		}
	}
	// field keySchema []*vitess.io/vitess/go/vt/proto/query.Field
	{
		size += hack.RuntimeAllocSize(int64(cap(cached.keySchema)) * int64(8))
		for _, elem := range cached.keySchema {
			size += elem.CachedSize(true)
		}
	}
	// field addrs []string
	{
		size += hack.RuntimeAllocSize(int64(cap(cached.addrs)) * int64(16))
		for _, elem := range cached.addrs {
			size += hack.RuntimeAllocSize(int64(len(elem)))
		}
	}
	// field shards []vitess.io/vitess/go/boost/boostpb.DRPCReaderClient
	{
		size += hack.RuntimeAllocSize(int64(cap(cached.shards)) * int64(16))
		for _, elem := range cached.shards {
			if cc, ok := elem.(cachedObject); ok {
				size += cc.CachedSize(true)
			}
		}
	}
	// field shardKeyType vitess.io/vitess/go/boost/boostpb.Type
	size += cached.shardKeyType.CachedSize(false)
	// field metrics *vitess.io/vitess/go/boost/topo/watcher.scopedMetrics
	size += cached.metrics.CachedSize(true)
	return size
}
func (cached *scopedMetrics) CachedSize(alloc bool) int64 {
	if cached == nil {
		return int64(0)
	}
	size := int64(0)
	if alloc {
		size += int64(32)
	}
	// field labels []string
	{
		size += hack.RuntimeAllocSize(int64(cap(cached.labels)) * int64(16))
		for _, elem := range cached.labels {
			size += hack.RuntimeAllocSize(int64(len(elem)))
		}
	}
	// field hitrate *vitess.io/vitess/go/boost/common/metrics.RateCounter
	if cached.hitrate != nil {
		size += hack.RuntimeAllocSize(int64(57))
	}
	return size
}
