// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: controller.proto

package boostpb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ReuseType int32

const (
	ReuseType_FINKELSTEIN ReuseType = 0
	ReuseType_RELAXED     ReuseType = 1
	ReuseType_FULL        ReuseType = 2
	ReuseType_NO_REUSE    ReuseType = 3
)

var ReuseType_name = map[int32]string{
	0: "FINKELSTEIN",
	1: "RELAXED",
	2: "FULL",
	3: "NO_REUSE",
}

var ReuseType_value = map[string]int32{
	"FINKELSTEIN": 0,
	"RELAXED":     1,
	"FULL":        2,
	"NO_REUSE":    3,
}

func (x ReuseType) String() string {
	return proto.EnumName(ReuseType_name, int32(x))
}

func (ReuseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

type UpqueryMode int32

const (
	UpqueryMode_SELECT_GTID UpqueryMode = 0
	UpqueryMode_TRACK_GTID  UpqueryMode = 1
)

var UpqueryMode_name = map[int32]string{
	0: "SELECT_GTID",
	1: "TRACK_GTID",
}

var UpqueryMode_value = map[string]int32{
	"SELECT_GTID": 0,
	"TRACK_GTID":  1,
}

func (x UpqueryMode) String() string {
	return proto.EnumName(UpqueryMode_name, int32(x))
}

func (UpqueryMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

type DomainConfig struct {
	ConcurrentReplays  int           `protobuf:"varint,1,opt,name=concurrent_replays,json=concurrentReplays,proto3,casttype=int" json:"concurrent_replays,omitempty"`
	ReplayBatchTimeout time.Duration `protobuf:"bytes,2,opt,name=replay_batch_timeout,json=replayBatchTimeout,proto3,stdduration" json:"replay_batch_timeout"`
	UpqueryMode        UpqueryMode   `protobuf:"varint,3,opt,name=upquery_mode,json=upqueryMode,proto3,enum=controller.UpqueryMode" json:"upquery_mode,omitempty"`
}

func (m *DomainConfig) Reset()         { *m = DomainConfig{} }
func (m *DomainConfig) String() string { return proto.CompactTextString(m) }
func (*DomainConfig) ProtoMessage()    {}
func (*DomainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}
func (m *DomainConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DomainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DomainConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DomainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainConfig.Merge(m, src)
}
func (m *DomainConfig) XXX_Size() int {
	return m.Size()
}
func (m *DomainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DomainConfig proto.InternalMessageInfo

type Config struct {
	Shards         uint          `protobuf:"varint,1,opt,name=shards,proto3,casttype=uint" json:"shards,omitempty"`
	PartialEnabled bool          `protobuf:"varint,2,opt,name=partial_enabled,json=partialEnabled,proto3" json:"partial_enabled,omitempty"`
	DomainConfig   *DomainConfig `protobuf:"bytes,4,opt,name=domain_config,json=domainConfig,proto3" json:"domain_config,omitempty"`
	// persistence = 5;
	HeartbeatEvery    time.Duration `protobuf:"bytes,6,opt,name=heartbeat_every,json=heartbeatEvery,proto3,stdduration" json:"heartbeat_every"`
	HealthcheckEvery  time.Duration `protobuf:"bytes,7,opt,name=healthcheck_every,json=healthcheckEvery,proto3,stdduration" json:"healthcheck_every"`
	Quorum            uint          `protobuf:"varint,8,opt,name=quorum,proto3,casttype=uint" json:"quorum,omitempty"`
	Reuse             ReuseType     `protobuf:"varint,9,opt,name=reuse,proto3,enum=controller.ReuseType" json:"reuse,omitempty"`
	EvictEvery        time.Duration `protobuf:"bytes,10,opt,name=evict_every,json=evictEvery,proto3,stdduration" json:"evict_every"`
	WorkerReadTimeout time.Duration `protobuf:"bytes,11,opt,name=worker_read_timeout,json=workerReadTimeout,proto3,stdduration" json:"worker_read_timeout"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Config.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return m.Size()
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("controller.ReuseType", ReuseType_name, ReuseType_value)
	proto.RegisterEnum("controller.UpqueryMode", UpqueryMode_name, UpqueryMode_value)
	proto.RegisterType((*DomainConfig)(nil), "controller.DomainConfig")
	proto.RegisterType((*Config)(nil), "controller.Config")
}

func init() { proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f) }

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6f, 0xd3, 0x4c,
	0x14, 0xb4, 0x9b, 0x7c, 0x69, 0xfa, 0x9c, 0x2f, 0x75, 0x97, 0x22, 0x4c, 0x0f, 0x4e, 0xe8, 0x85,
	0xaa, 0x48, 0x8e, 0x54, 0x24, 0x0e, 0x48, 0x08, 0x35, 0x8d, 0x8b, 0xaa, 0x86, 0x82, 0x36, 0x89,
	0x84, 0xb8, 0x58, 0x6b, 0xfb, 0x35, 0xb1, 0xea, 0x78, 0xd3, 0xcd, 0xba, 0x28, 0xff, 0x82, 0x23,
	0x07, 0x7e, 0x50, 0x8f, 0x3d, 0xc2, 0xa5, 0x40, 0xfb, 0x2f, 0x7a, 0x42, 0xf1, 0xba, 0x8d, 0xc5,
	0x29, 0x17, 0x6b, 0x77, 0xf6, 0xcd, 0x68, 0x66, 0xfc, 0xc0, 0x0c, 0x78, 0x22, 0x05, 0x8f, 0x63,
	0x14, 0xce, 0x44, 0x70, 0xc9, 0x09, 0x2c, 0x90, 0xad, 0xcd, 0x21, 0x1f, 0xf2, 0x0c, 0x6e, 0xcd,
	0x4f, 0x6a, 0x62, 0xcb, 0x1e, 0x72, 0x3e, 0x8c, 0xb1, 0x95, 0xdd, 0xfc, 0xf4, 0xb4, 0x15, 0xa6,
	0x82, 0xc9, 0x88, 0x27, 0xea, 0x7d, 0xfb, 0xa7, 0x0e, 0xb5, 0x0e, 0x1f, 0xb3, 0x28, 0x39, 0xe0,
	0xc9, 0x69, 0x34, 0x24, 0xaf, 0x80, 0x04, 0x3c, 0x09, 0x52, 0x21, 0x30, 0x91, 0x9e, 0xc0, 0x49,
	0xcc, 0x66, 0x53, 0x4b, 0x6f, 0xea, 0x3b, 0xa5, 0xf6, 0xea, 0xdd, 0x75, 0xa3, 0x14, 0x25, 0x92,
	0x6e, 0x2c, 0x46, 0xa8, 0x9a, 0x20, 0x03, 0xd8, 0x54, 0xc3, 0x9e, 0xcf, 0x64, 0x30, 0xf2, 0x64,
	0x34, 0x46, 0x9e, 0x4a, 0x6b, 0xa5, 0xa9, 0xef, 0x18, 0x7b, 0x4f, 0x1d, 0xe5, 0xc3, 0xb9, 0xf7,
	0xe1, 0x74, 0x72, 0x1f, 0xed, 0xea, 0xe5, 0x75, 0x43, 0xfb, 0xf6, 0xab, 0xa1, 0x53, 0xa2, 0x04,
	0xda, 0x73, 0x7e, 0x5f, 0xd1, 0xc9, 0x6b, 0xa8, 0xa5, 0x93, 0xf3, 0x14, 0xc5, 0xcc, 0x1b, 0xf3,
	0x10, 0xad, 0x52, 0x53, 0xdf, 0xa9, 0xef, 0x3d, 0x71, 0x0a, 0x55, 0x0c, 0xd4, 0xfb, 0x7b, 0x1e,
	0x22, 0x35, 0xd2, 0xc5, 0x65, 0xfb, 0x7b, 0x19, 0x2a, 0x79, 0xaa, 0x26, 0x54, 0xa6, 0x23, 0x26,
	0x42, 0x95, 0xa4, 0xdc, 0xae, 0xde, 0x5d, 0x37, 0xca, 0xe9, 0x3c, 0x4a, 0x8e, 0x93, 0xe7, 0xb0,
	0x3e, 0x61, 0x42, 0x46, 0x2c, 0xf6, 0x30, 0x61, 0x7e, 0x8c, 0x61, 0x66, 0xbd, 0x4a, 0xeb, 0x39,
	0xec, 0x2a, 0x94, 0xbc, 0x81, 0xff, 0xc3, 0xac, 0x30, 0x2f, 0xc8, 0xb4, 0xad, 0x72, 0x96, 0xd0,
	0x2a, 0x5a, 0x2a, 0x36, 0x4a, 0x6b, 0x61, 0xb1, 0xdf, 0x2e, 0xac, 0x8f, 0x90, 0x09, 0xe9, 0x23,
	0x93, 0x1e, 0x5e, 0xa0, 0x98, 0x59, 0x95, 0xe5, 0x2b, 0xaa, 0x3f, 0x70, 0xdd, 0x39, 0x95, 0x7c,
	0x84, 0x8d, 0x11, 0xb2, 0x58, 0x8e, 0x82, 0x11, 0x06, 0x67, 0xb9, 0xde, 0xea, 0xf2, 0x7a, 0x66,
	0x81, 0xad, 0x14, 0x9b, 0x50, 0x39, 0x4f, 0xb9, 0x48, 0xc7, 0x56, 0xf5, 0xdf, 0xa6, 0x14, 0x4e,
	0x5e, 0xc0, 0x7f, 0x02, 0xd3, 0x29, 0x5a, 0x6b, 0xd9, 0xbf, 0x78, 0x5c, 0x0c, 0x4e, 0xe7, 0x0f,
	0xfd, 0xd9, 0x04, 0xa9, 0x9a, 0x21, 0x1d, 0x30, 0xf0, 0x22, 0x0a, 0xee, 0xa3, 0xc2, 0xf2, 0xd6,
	0x20, 0xe3, 0x29, 0x53, 0x3d, 0x78, 0xf4, 0x85, 0x8b, 0x33, 0x14, 0x9e, 0x40, 0x16, 0x3e, 0xec,
	0x96, 0xb1, 0xbc, 0xda, 0x86, 0xe2, 0x53, 0x64, 0x61, 0xbe, 0x5a, 0xbb, 0xfb, 0xb0, 0xf6, 0x60,
	0x97, 0xac, 0x83, 0x71, 0x78, 0x74, 0x72, 0xec, 0x76, 0x7b, 0x7d, 0xf7, 0xe8, 0xc4, 0xd4, 0x88,
	0x01, 0xab, 0xd4, 0xed, 0xee, 0x7f, 0x72, 0x3b, 0xa6, 0x4e, 0xaa, 0x50, 0x3e, 0x1c, 0x74, 0xbb,
	0xe6, 0x0a, 0xa9, 0x41, 0xf5, 0xe4, 0x83, 0x47, 0xdd, 0x41, 0xcf, 0x35, 0x4b, 0xbb, 0x0e, 0x18,
	0x85, 0xed, 0x9b, 0x8b, 0xf4, 0xdc, 0xae, 0x7b, 0xd0, 0xf7, 0xde, 0xf5, 0x8f, 0x3a, 0xa6, 0x46,
	0xea, 0x00, 0x7d, 0xba, 0x7f, 0x70, 0xac, 0xee, 0x7a, 0xfb, 0xed, 0xe5, 0x1f, 0x5b, 0xbb, 0xbc,
	0xb1, 0xf5, 0xab, 0x1b, 0x5b, 0xff, 0x7d, 0x63, 0xeb, 0x5f, 0x6f, 0x6d, 0xed, 0xea, 0xd6, 0xd6,
	0x7e, 0xdc, 0xda, 0xda, 0xe7, 0x67, 0x17, 0x91, 0xc4, 0xe9, 0xd4, 0x89, 0x78, 0x4b, 0x9d, 0x5a,
	0x43, 0xde, 0xf2, 0x39, 0x9f, 0x4a, 0xf5, 0x9d, 0xf8, 0x7e, 0x25, 0xcb, 0xf8, 0xf2, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xcb, 0x82, 0xc1, 0xb5, 0x0b, 0x04, 0x00, 0x00,
}

func (m *DomainConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DomainConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DomainConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpqueryMode != 0 {
		i = encodeVarintController(dAtA, i, uint64(m.UpqueryMode))
		i--
		dAtA[i] = 0x18
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.ReplayBatchTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.ReplayBatchTimeout):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintController(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.ConcurrentReplays != 0 {
		i = encodeVarintController(dAtA, i, uint64(m.ConcurrentReplays))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Config) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Config) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n2, err2 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.WorkerReadTimeout, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.WorkerReadTimeout):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintController(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x5a
	n3, err3 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.EvictEvery, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.EvictEvery):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintController(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x52
	if m.Reuse != 0 {
		i = encodeVarintController(dAtA, i, uint64(m.Reuse))
		i--
		dAtA[i] = 0x48
	}
	if m.Quorum != 0 {
		i = encodeVarintController(dAtA, i, uint64(m.Quorum))
		i--
		dAtA[i] = 0x40
	}
	n4, err4 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.HealthcheckEvery, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.HealthcheckEvery):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintController(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x3a
	n5, err5 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.HeartbeatEvery, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.HeartbeatEvery):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintController(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x32
	if m.DomainConfig != nil {
		{
			size, err := m.DomainConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintController(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.PartialEnabled {
		i--
		if m.PartialEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Shards != 0 {
		i = encodeVarintController(dAtA, i, uint64(m.Shards))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintController(dAtA []byte, offset int, v uint64) int {
	offset -= sovController(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DomainConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConcurrentReplays != 0 {
		n += 1 + sovController(uint64(m.ConcurrentReplays))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.ReplayBatchTimeout)
	n += 1 + l + sovController(uint64(l))
	if m.UpqueryMode != 0 {
		n += 1 + sovController(uint64(m.UpqueryMode))
	}
	return n
}

func (m *Config) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Shards != 0 {
		n += 1 + sovController(uint64(m.Shards))
	}
	if m.PartialEnabled {
		n += 2
	}
	if m.DomainConfig != nil {
		l = m.DomainConfig.Size()
		n += 1 + l + sovController(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.HeartbeatEvery)
	n += 1 + l + sovController(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.HealthcheckEvery)
	n += 1 + l + sovController(uint64(l))
	if m.Quorum != 0 {
		n += 1 + sovController(uint64(m.Quorum))
	}
	if m.Reuse != 0 {
		n += 1 + sovController(uint64(m.Reuse))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.EvictEvery)
	n += 1 + l + sovController(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.WorkerReadTimeout)
	n += 1 + l + sovController(uint64(l))
	return n
}

func sovController(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozController(x uint64) (n int) {
	return sovController(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DomainConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowController
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DomainConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DomainConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConcurrentReplays", wireType)
			}
			m.ConcurrentReplays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConcurrentReplays |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplayBatchTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.ReplayBatchTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpqueryMode", wireType)
			}
			m.UpqueryMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpqueryMode |= UpqueryMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipController(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthController
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Config) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowController
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shards", wireType)
			}
			m.Shards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Shards |= uint(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartialEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PartialEnabled = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DomainConfig == nil {
				m.DomainConfig = &DomainConfig{}
			}
			if err := m.DomainConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatEvery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.HeartbeatEvery, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HealthcheckEvery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.HealthcheckEvery, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quorum", wireType)
			}
			m.Quorum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quorum |= uint(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reuse", wireType)
			}
			m.Reuse = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reuse |= ReuseType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvictEvery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.EvictEvery, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerReadTimeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowController
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthController
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthController
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.WorkerReadTimeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipController(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthController
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipController(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowController
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowController
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowController
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthController
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupController
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthController
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthController        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowController          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupController = fmt.Errorf("proto: unexpected end of group")
)
