on:
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron:  '*/5 * * * *'

jobs:
  analyze:
    name: analyze_check_runs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: metrics
    - name: analyze check runs
      run: |
        GITHUB_REPOSITORY="vitessio/vitess"
        FAILED_RUNS_JSON="/tmp/failed_runs.json"
        FAILED_RUNS_CSV="/tmp/failed_runs.csv"
        FAILED_RUNS_COMBINED="/tmp/failed_runs.csv"
        WORKFLOW_FAILURES_FILE=".metrics/workflow-failures"

        ls -l $WORKFLOW_FAILURES_FILE

        curl \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-type: application/json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?per_page=100&status=failure" \
          > "$FAILED_RUNS_JSON"

        cat "$FAILED_RUNS_JSON" |
          jq -r '.workflow_runs[] | (.created_at + "," + .name + "," + .html_url)' > "$FAILED_RUNS_CSV"

        tmpfile="$(mktemp)"
        cat $WORKFLOW_FAILURES_FILE $FAILED_RUNS_CSV | sort | uniq > $tmpfile

        cat $tmpfile
    - name: push to metrics branch
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'metrics'
        commit-message: 'append failed workflow runs metrics'
        force-add: 'true'
        files: .metrics/workflow-failures
        name: planetscalebot
        email: planetscalebot@planetscale.com
