on:
  check_run:
    types: [completed]

jobs:

  analyze:
    name: Analyze and report failed check runs
    runs-on: ubuntu-latest
    steps:
      - name: analyze check run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONCLUSION1: ${{ github.event.check_run[conclusion] }}
        CONCLUSION2: ${{ github.event.check_run.conclusion }}
        CHECK_RUN: ${{ github.event.check_run }}
      run: |
        echo "cehck run is: $CHECK_RUN"
        echo "conclusions are: 1=$CONCLUSION1, 2=$CONCLUSION2"
      
