on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  analyze:
    name: analyze_check_runs
    runs-on: ubuntu-latest
    steps:
    - name: get hub
      run: |
        cd /tmp
        curl -s -L https://github.com/github/hub/releases/download/v2.12.3/hub-linux-amd64-2.12.3.tgz > hub-linux-amd64-2.12.3.tgz
        tar xzf hub-linux-amd64-2.12.3.tgz hub-linux-amd64-2.12.3/bin/hub
        mv hub-linux-amd64-2.12.3/bin/hub hub

    - uses: actions/checkout@v2
      with:
        ref: metrics
    - name: analyze check runs
      run: |
        # GITHUB_REPOSITORY="vitessio/vitess"
        FAILED_RUNS_JSON="/tmp/failed_runs.json"
        FAILED_RUNS_CSV="/tmp/failed_runs.csv"
        FAILED_RUNS_COMBINED="/tmp/failed_runs.csv"
        WORKFLOW_FAILURES_FILE=".metrics/workflow-failures"

        echo "> GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "git branch:"
        git branch
        echo "ls -l $WORKFLOW_FAILURES_FILE:"
        ls -l "$WORKFLOW_FAILURES_FILE"

        # Get latest failed check runs
        curl \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-type: application/json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?per_page=100&status=failure" \
          > "$FAILED_RUNS_JSON"

        # extract .created_at, .name, .html_url for each failed check run
        cat "$FAILED_RUNS_JSON" |
          jq -r '.workflow_runs[] | (.created_at + "," + .name + "," + .html_url)' > "$FAILED_RUNS_CSV"

        # now combine back into $WORKFLOW_FAILURES_FILE, skipping duplicates
        tmpfile="$(mktemp)"
        cat $WORKFLOW_FAILURES_FILE $FAILED_RUNS_CSV | sort | uniq | base64 -w 0 > $tmpfile
        sha="$(sha1sum < $tmpfile | cut -d' ' -f1)"
        sha="$(git hash-object $tmpfile)"
        sha="$(printf "blob $(cat $tmpfile | wc -c)\0$(cat $tmpfile)" | sha1sum)"
        sha="$(git hash-object ${WORKFLOW_FAILURES_FILE})"
        # cp $tmpfile $WORKFLOW_FAILURES_FILE

        json="
          {
            \"message\": \"automated merge of failed check runs\",
            \"branch\": \"metrics\",
            \"sha\": \"$sha\",
            \"content\": \"$(cat $tmpfile)\"
          }
        "

        echo "> json is:"
        echo "$json"

        curl \
          -X PUT \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-type: application/json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/contents/${WORKFLOW_FAILURES_FILE}" \
          -d "$json"
