name: cluster_endtoend
on: [push, pull_request]
jobs:

  build:
    name: Cluster End-to-End Test for Shard 12
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget
        sudo service mysql stop
        sudo service etcd stop
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        go mod download

    - name: cluster_endtoend_shard_12
      run: |
        source build.env
        echo $VTDATAROOT
        go run test.go -docker=false -print-log -shard 12
