name: Cluster (upgrade)
on: [push, pull_request]
jobs:

  build:
    if: github.repository == 'vitessio/vitess'
    name: Run endtoend tests on Cluster (upgrade)
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Check out to HEAD
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get latest Vitess tag
      run: |
        echo "latest_release=v$(git show-ref --tags | grep -E 'refs/tags/v[0-9]*.[0-9]*.[0-9]*$' | sed 's/[a-z0-9]* refs\/tags\/v//' | sort -nr | head -n1)" >> $GITHUB_ENV

    - name: Tune the OS
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

    - name: Check out ${{ env.latest_release }}
      uses: actions/checkout@v2
      with:
        ref: ${{ env.latest_release }}

    - name: Get dependencies
      run: |
        # This prepares general purpose binary dependencies
        # as well as latest version specific go modules
        sudo apt-get update
        sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget eatmydata
        sudo service mysql stop
        sudo service etcd stop
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        go mod download

        wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
        sudo apt-get install -y gnupg2
        sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
        sudo apt-get update
        sudo apt-get install percona-xtrabackup-24

    - name: Building ${{ env.latest_release }} binaries
      timeout-minutes: 10
      run: |
        # We build latest version binaries and save them in a temporary location
        source build.env
        make build
        mkdir -p /tmp/vitess-build-${{ env.latest_release }}/
        cp -R bin /tmp/vitess-build-${{ env.latest_release }}/

    - name: Check out HEAD
      uses: actions/checkout@v2

    - name: Run cluster endtoend test ${{ env.latest_release }} (create cluster)
      timeout-minutes: 5
      run: |
        # By checking out we deleted bin/ directory. We now restore our pre-built latest version binaries
        cp -R /tmp/vitess-build-${{ env.latest_release }}/bin .
        # create the directory where we store test data; ensure it is empty:
        rm -rf /tmp/vtdataroot
        mkdir -p /tmp/vtdataroot
        source build.env
        # We pass -skip-build so that we use the latest version binaries, not HEAD binaries
        eatmydata -- go run test.go -skip-build -keep-data -docker=false -print-log -follow -shard 28

    - name: Check out HEAD
      uses: actions/checkout@v2


    - name: Building HEAD binaries
      timeout-minutes: 10
      run: |
        go mod download

        source build.env
        make build
        mkdir -p /tmp/vitess-build-head/
        cp -R bin /tmp/vitess-build-head/

    - name: Run cluster endtoend test HEAD based on ${{ env.latest_release }} data (upgrade path)
      timeout-minutes: 5
      run: |
        # /tmp/vtdataroot exists from previous test

        source build.env
        # We built HEAD binaries manually in previous step and there's no need for the test to build.
        eatmydata -- go run test.go -skip-build -keep-data -docker=false -print-log -follow -shard 28

    - name: Run cluster endtoend test HEAD (create cluster)
      timeout-minutes: 5
      run: |
        # create the directory where we store test data; ensure it is empty:
        rm -rf /tmp/vtdataroot
        mkdir -p /tmp/vtdataroot

        source build.env
        # We still have the binaries from previous step. No need to build
        eatmydata -- go run test.go -skip-build -keep-data -docker=false -print-log -follow -shard 28


    - name: Run cluster endtoend test ${{ env.latest_release }} based on HEAD data (downgrade path)
      timeout-minutes: 5
      run: |
        # /tmp/vtdataroot exists from previous test
        cp -R /tmp/vitess-build-${{ env.latest_release }}/bin .

        source build.env
        # We again built manually and there's no need for the test to build.
        eatmydata -- go run test.go -skip-build -keep-data -docker=false -print-log -follow -shard 28
