name: docker_test_cluster_10
on: [push]
jobs:

  build:
    name: Docker Test Cluster 10
    runs-on: ubuntu-latest

    steps:
      - name: Configure git private repo access
        env:
          GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for changes in relevant files
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          token: ''
          filters: |
            end_to_end:
              - 'go/**/*.go'
              - 'test.go'
              - 'Makefile'
              - 'build.env'
              - 'go.sum'
              - 'go.mod'
              - 'proto/*.proto'
              - 'tools/**'
              - 'config/**'
              - 'bootstrap.sh'
              - 'docker/**'
              - '.github/workflows/docker_test_cluster_10.yml'

      - name: Set up Go
        if: steps.changes.outputs.end_to_end == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.13

      - name: Tune the OS
        if: steps.changes.outputs.end_to_end == 'true'
        run: |
          sudo sysctl -w net.ipv4.ip_local_port_range="22768 65535"

      - name: Run tests which require docker - 1
        if: steps.changes.outputs.end_to_end == 'true'
        run: |
          go run test.go -docker=true --follow -shard 10
