name: docker_test_cluster_10
on: [push]
jobs:

  build:
    name: Docker Test Cluster 10
    runs-on: ubuntu-latest

    steps:
      - name: Configure git private repo access
        env:
          GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20.13

      - name: Tune the OS
        run: |
          sudo sysctl -w net.ipv4.ip_local_port_range="22768 65535"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests which require docker - 1
        run: |
          go run test.go -docker=true --follow -shard 10
