name: e2e_race
on: [push]
jobs:

  build:
    name: End-to-End Test (Race)
    runs-on: ubuntu-latest
    steps:
    - name: Configure git private repo access
      env:
        GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
      run: |
        git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1

    - name: Tune the OS
      run: |
        sudo sysctl -w net.ipv4.ip_local_port_range="22768 65535"

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      env: # Or as an environment variable
        AWS_ACCESS_KEY_ID: ${{ secrets.BUILDKITE_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILDKITE_S3_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        sudo apt-get update
        # stop any existing running instance of mysql
        sudo service mysql stop
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

        # Uninstall any previously installed MySQL first
        sudo DEBIAN_FRONTEND="noninteractive" apt-get remove -y --purge mysql-server mysql-client mysql-common
        sudo apt-get -y autoremove
        sudo apt-get -y autoclean
        sudo deluser mysql
        sudo rm -rf /var/lib/mysql
        sudo rm -rf /etc/mysql

        # install necessary tools
        sudo apt-get install -y make unzip g++ etcd curl git wget awscli
        sudo service etcd stop

        # Get latest version of mysql from s3 bucket
        LATEST_BUILD=$(aws s3api list-objects-v2 --bucket "planetscale-mysql-server-private-ci-artifacts" --prefix mysql/main/dist --query 'reverse(sort_by(Contents[?contains(Key, `focal`)], &LastModified))[:1].Key' --output=text)
        echo "latest build is $LATEST_BUILD"
        # Pin this to 8.0.30
        LAST_BUILD="mysql/main/dist/mysql-8.0.30.20221013-ps-87805bf371e-focal-linux-x86_64.tar.gz"
        echo "installing psdb mysql $LAST_BUILD"
        aws s3 cp "s3://planetscale-mysql-server-private-ci-artifacts/${LAST_BUILD}" .
        sudo tar xf $(basename $LAST_BUILD) -v -C /usr --strip-components=1

        # Install everything else we need, and configure
        sudo apt-get install -y mysql-server mysql-client eatmydata
        sudo service mysql stop
        sudo service etcd stop
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        go mod download

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: e2e_race
      timeout-minutes: 30
      run: |
        make e2e_test_race
