name: endtoend
on: [push, pull_request]
jobs:

  build:
    name: End-to-End Test
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.9

    - name: Tune the OS
      run: |
        echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

    - name: Get dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget
        sudo service mysql stop
        sudo service etcd stop
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        go mod download

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: Build
      run: |
        make build

    - name: endtoend
      timeout-minutes: 30
      run: |
        eatmydata -- tools/e2e_test_runner.sh
