name: Get Dependencies
on:
  workflow_call:

jobs:
  get_dependencies:
    name: Get Dependencies
    runs-on: ubuntu-18.04

    steps:
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget eatmydata
          sudo service mysql stop
          sudo service etcd stop
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
          go mod download

          # install JUnit report formatter
          go get -u github.com/vitessio/go-junit-report@HEAD

          wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
          sudo apt-get install -y gnupg2
          sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
          sudo apt-get update
          sudo apt-get install percona-xtrabackup-24