name: java_test
on: [push, pull_request]
jobs:

  build:
    name: Java Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run java test
      run: |
        go run test.go -docker=true java