name: local_example
on: [push, pull_request]
jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-latest, macos-latest, centos-latest]

    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        if [ ${{matrix.TARGET}} = "ubuntu-latest"]; then
          sudo apt-get install -y mysql-server mysql-client make unzip g++ etcd curl git wget
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
        elif [ ${{matrix.TARGET}} = "macos-latest" ]; then
          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
          brew install mysql@5.7 make unzip etcd curl git wget
        elif [ ${{matrix.TARGET}} = "centos-latest" ]; then
          yum update 
          sudo yum install mysql-community-server mysql-client unzip g++ etcd curl git wget
        else exit 1;
        fi
        sudo service mysql stop
        sudo service etcd stop

        go mod download

    - name: Run make minimaltools
      run: |
        make minimaltools

    - name: Build
      run: |
        make build

    - name: local_example
      run: |
        test/local_example.sh

