name: Static Code Checks, Etc.

on:
  - push

permissions: read-all

jobs:
  build:
    name: Static Code Checks Etc
    runs-on: ubuntu-latest

    steps:
      - name: Configure git private repo access
        env:
          GITHUB_TOKEN: ${{ secrets.PLANETSCALE_ACTIONS_BOT_TOKEN }}
        run: |
          git config --global --add url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 76d7483ea206d530d9452e44bffe7ba8

      - name: Check for changes in Go files
        uses: frouioui/paths-filter@main
        id: changes
        with:
          token: ''
          filters: |
            go_files:
              - '**/*.go'
              - '*.go'
              - 'go.[sumod]'
              - '.github/workflows/static_checks_etc.yml'
            parser_changes:
              - 'go/vt/sqlparser/**'
              - 'go.[sumod]'
              - 'build.env'
              - 'bootstrap.sh'
              - 'tools/**'
              - '.github/workflows/static_checks_etc.yml'
            proto_changes:
              - 'bootstrap.sh'
              - 'tools/**'
              - 'build.env'
              - 'go.[sumod]'
              - 'Makefile'
              - 'go/vt/proto/**'
              - 'proto/*.proto'
              - '.github/workflows/static_checks_etc.yml'
            sizegen:
              - 'go/**/*.go'
              - 'test.go'
              - 'Makefile'
              - 'build.env'
              - 'go.[sumod]'
              - 'tools/**'
              - 'bootstrap.sh'
              - '.github/workflows/static_checks_etc.yml'
            visitor:
              - 'go/tools/asthelpergen/**'
              - 'go/vt/sqlparser/**'
              - 'Makefile'
              - 'build.env'
              - 'go.[sumod]'
              - 'tools/**'
              - 'bootstrap.sh'
              - 'misc/git/hooks/asthelpers'
              - '.github/workflows/static_checks_etc.yml'
            end_to_end:
              - 'docker/**'
              - 'test.go'
              - 'Makefile'
              - 'bootstrap.sh'
              - '.github/workflows/static_checks_etc.yml'


      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Tune the OS
        run: |
          echo '1024 65535' | sudo tee -a /proc/sys/net/ipv4/ip_local_port_range

      - name: Run go fmt
        run: |
          gofmt -l . | grep -vF vendor/ && exit 1 || echo "All files formatted correctly"

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run goimports
        run: |
          out=$(goimports -local vitess.io/vitess -l -w $(find . -name "*.go" -not -path "./go/test/go-mysql-server/*" -not -path "*.pb.go"))
          echo $out | grep go > /dev/null && echo -e "The following files are malformatted:\n$out" && exit 1 || echo "All the files are formatted correctly"

      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make unzip g++ etcd curl git wget
          sudo service etcd stop
          go mod download

      - name: Run make minimaltools
        run: |
          make minimaltools

      - name: check_make_parser
        run: |
          tools/check_make_parser.sh || exit 1

      - name: check_make_sizegen
        run: |
          tools/check_make_sizegen.sh || exit 1

      - name: check_make_visitor
        run: |
          misc/git/hooks/asthelpers || exit 1

      - name: run ensure_bootstrap_version
        run: |
          make ensure_bootstrap_version
          git status
          test -z "$(git diff-index --name-only HEAD --)" || exit 1

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      ## Go files
      - name: Run go fmt
        run: |
          gofmt -l . | grep -vF go/test/go-mysql-server/ && exit 1 || echo "All files formatted correctly"

      - name: Run goimports
        run: |
          out=$(goimports -local vitess.io/vitess -l -w $(find . -name "*.go" -not -path "./go/test/go-mysql-server/*" -not -path "*.pb.go"))
          echo $out | grep go > /dev/null && echo -e "The following files are malformatted:\n$out" && exit 1 || echo "All the files are formatted correctly"

      - name: Clean Env
        run: $(go env GOPATH)/bin/golangci-lint cache clean

      - name: Print linter version
        run: $(go env GOPATH)/bin/golangci-lint --version

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run go/... || exit 1

      - name: Run go mod tidy
        run: |
          set -e
          go mod tidy
          output=$(git status -s)
          if [ -z "${output}" ]; then
            exit 0
          fi
          echo 'We wish to maintain a tidy state for go mod. Please run `go mod tidy` on your branch, commit and push again.'
          echo 'Running `go mod tidy` on this CI test yields with the following changes:'
          echo "$output"
          exit 1

      - name: check_make_proto
        run: |
          tools/check_make_proto.sh || exit 1
