name: Update Golang Version

on:
  # Triggers the workflow every day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_golang_version:
    name: Update Golang Version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Detect new version and update codebase
        run:

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "upgrade vitess dependency to latest"
          signoff: true
          delete-branch: true
          title: "Upgrade Vitess Dependency to Latest"
          body: "Weekly Vitess dependency upgrade running on a cron schedule"
          reviewers: |
            frouioui
            GuptaManan100
