name: vtadmin-web build

# In specifying the 'paths' property, we need to include the path to this workflow .yml file. 
# See https://github.community/t/trigger-a-workflow-on-change-to-the-yml-file-itself/17792/4)
on:
  push:
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'
  pull_request:
    paths:
      - '.github/workflows/vtadmin_web_build.yml'
      - 'web/vtadmin/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          # node-version should match package.json
          node-version: '16.13.0'

      - name: Install dependencies
        run: cd ./web/vtadmin && npm ci

      - name: Build front-end
        run: cd ./web/vtadmin && npm run build

    # Cancel pending and in-progress runs of this workflow if a newer ref is pushed to CI.
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
